# Generated by Django 4.0.5 on 2022-06-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_child',
            name='parent',
            field=models.ForeignKey(db_column='parent_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
