# Generated by Django 4.0.5 on 2022-06-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_child_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
